import type { Metadata } from 'next';
import { SITE_URL } from './site-url';

export const SITE_NAME = 'Symtera Technologies';

/** The title template in app/layout.tsx, applied here for og:title and twitter:title. */
export const fullTitle = (title: string) => (title === SITE_NAME ? title : `${title} — ${SITE_NAME}`);

export const absoluteUrl = (path: string) => (path === '/' ? SITE_URL : `${SITE_URL}${path}`);

/** Branded 1200x630 share card, generated by app/og/route.tsx. */
const OG_IMAGE = {
  url: `${SITE_URL}/og`,
  width: 1200,
  height: 630,
  alt: 'Symtera Technologies — intelligent systems, built for scale and security',
};

/** Per-page metadata: self-referencing canonical, Open Graph and Twitter card. */
export function pageMetadata({
  title,
  description,
  path,
  absolute = false,
}: {
  /** Page title without the brand suffix; the layout template adds it. */
  title: string;
  description: string;
  path: string;
  /** Home page only: use the title as given instead of the layout template. */
  absolute?: boolean;
}): Metadata {
  const url = absoluteUrl(path);
  const ogTitle = absolute ? title : fullTitle(title);
  return {
    title: absolute ? { absolute: title } : title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title: ogTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: 'en_US',
      type: 'website',
      images: [OG_IMAGE],
    },
    twitter: {
      card: 'summary_large_image',
      title: ogTitle,
      description,
      images: [OG_IMAGE.url],
    },
  };
}
